### ISSUE TITLE
Autolinks - URls within HTML produces invalid HTML

### ISSUE THREAD

**Issue by edent** [thephpleague/commonmark#1045]
### Version(s) affected

2.5

### Description

In this HTML, the autolinker adds a nested `<a>` which is invalid.

`HTML <a href="https://example.com">Visit https://example.com</a>`

Becomes

```html
<p>HTML <a href="https://example.com">Visit <a href="https://example.com">https://example.com</a></a></p>
```

I would expect the autolinker to ignore the URl inside the anchor.  For example, this produces correct HTML:

`[Visit https://example.com](https://example.com)`

### How to reproduce

As per https://commonmark.thephpleague.com/2.5/extensions/autolinks/

```php
require_once 'vendor/autoload.php';

use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\Autolink\AutolinkExtension;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\MarkdownConverter;

// Define your configuration, if needed
$config = [];

// Configure the Environment with all the CommonMark parsers/renderers
$environment = new Environment($config);
$environment->addExtension(new CommonMarkCoreExtension());

// Add this extension
$environment->addExtension(new AutolinkExtension());

// Instantiate the converter engine and start converting some Markdown!
$converter = new MarkdownConverter($environment);

echo $converter->convert('Correct [Visit https://example.com](https://example.com)');
echo $converter->convert('Broken <a href="https://example.com">Visit https://example.com</a>');
```

**Comment by colinodell** [comment]
The Autolink extension follows [the GFM spec](https://github.github.com/gfm/#autolinks-extension-) which unfortunately doesn't make exceptions for autolinks found inside of HTML.  You can see [here](https://babelmark.github.io/?text=HTML+%3Ca+href%3D%22https%3A%2F%2Fexample.com%22%3EVisit+https%3A%2F%2Fexample.com%3C%2Fa%3E) that the official GFM parser behaves somewhat similarly, giving this output:

```html
<p>
  HTML <a href="https://example.com" rel="nofollow">Visit 
  </a><a href="https://example.com" rel="nofollow">https://example.com
  </a>
</p>
```

So because this behavior matches both the spec and the official GFM parser I'm inclined to keep this as-is for now.  But if they change this upstream in their specification I'd be glad to make this change here to remain aligned with them!

Thanks for the detailed report, though!

**Comment by edent** [comment]
Thanks - that's pretty reasonable.
