### ISSUE TITLE
Preserving entities on fenced code blocks

### ISSUE THREAD

**Issue by alexgarrett** [thephpleague/commonmark#113]
If output is properly escaped prior to a fenced code block being rendered, shouldn't this renderer preserve entities? Otherwise, this causes problems with syntax highlighters like Prism.js.

https://github.com/thephpleague/commonmark/blob/master/src/Block/Renderer/FencedCodeRenderer.php#L45

If this makes sense, I'll PR.

**Comment by colinodell** [comment]
According to [the spec](http://spec.commonmark.org/0.20/#example-249), entities within code blocks/spans aren't converted to Unicode characters ([like they would if they appeared elsewhere](http://spec.commonmark.org/0.20/#entities)).  The HTML renderer escapes the entities so that their appearance within the Markdown document matches their HTML appearance (using valid HTML).

Here are a couple examples showing that behavior:

* [JavaScript reference implementation](http://spec.commonmark.org/dingus/?text=%26ngE%3B%0A%0A%26gE%3B)
* [The same input run through several different parsers](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%E2%89%A7%0A%0A%26gE%3B%0A%0A~~~php%0A%24foo+%3D+%27%E2%89%A7%27%3B%0A%24bar+%3D+%27%26gE%3B%27%3B%0A~~~%0A)

It sounds like the behavior of this library is consistent with the CommonMark spec.

If this doesn't really answer your question, perhaps you could provide some example input and what you'd expect the output to be?

**Comment by alexgarrett** [comment]
@colinodell That makes total sense, sorry, I didn't check the spec properly.

The actual issue here is that if output is already properly escaped, &amp; will be double encoded to &amp;amp;, meaning front-end libraries for syntax highlighting won't be able to render entities properly unless something is modified front-end.

Is there a common solution to this problem you know of?

**Comment by colinodell** [comment]
Ah okay, I see what you're getting at.  Because the double-escaping behavior seems correct to me (from and HTML output persepective), I'm going to mark this as closed.

I found some references where folks just decode the entities themselves before highlighting; for example: http://blog.awesomebox.net/highlighting-code-in-ghost/#decodingthecode  You'll probably have to do something similar in order to convert the HTML representation into the "raw".

It may be worthwhile to check out the PrismJS project too: https://github.com/PrismJS/prism/issues  Maybe browse the issues/PRs for anything related to double-encoding, or perhaps open a new one?

Hopefully that helps!

**Comment by mAAdhaTTah** [comment]
Prism doesn't do any escaping. You have to escape the html entities yourself before Prism highlights it. Otherwise, the html is rendered by the browser.
