### ISSUE TITLE
Request: Convert to plain text

### ISSUE THREAD

**Issue by grandnasty** [thephpleague/commonmark#114]
It would be great to have a convertToText() function. This would allow one to take markdown formatted input and obtain it as plain text. Scenario for this could be for example previews (showing first X words) where formatting is not always wanted.

Great work on this commonmark project! Much appreciated.

**Comment by cebe** [comment]
why not just use strip_tags() on the output?

**Comment by grandnasty** [comment]
I suppose that it would be more efficient not having to go through the full rendering in HTML and then re-render it to plain text. But for non-"high performance" applications this is a great suggestion. Thanks.

**Comment by cebe** [comment]
if you need high performance you should pre-render the markdown anyway.

**Comment by colinodell** [comment]
I wrote a quick script to benchmark the conversion process (using [this sample file](https://github.com/thephpleague/commonmark/blob/master/tests/benchmark/sample.md)):

~~~php
#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use League\CommonMark\Environment;
use League\CommonMark\DocParser;
use League\CommonMark\HtmlRenderer;

$markdown = file_get_contents(__DIR__ . '/tests/benchmark/sample.md');

$environment = Environment::createCommonMarkEnvironment();
$parser = new DocParser($environment);
$renderer = new HtmlRenderer($environment);

$start = microtime(true);
$ast = $parser->parse($markdown);
printf("Parsed the Markdown in %0.2f ms\n", (microtime(true) - $start)*1000);

$start = microtime(true);
$html = $renderer->renderBlock($ast);
printf("Rendered the HTML in %0.2f ms\n", (microtime(true) - $start)*1000);

$start = microtime(true);
$stripped = strip_tags($html);
printf("Stripped tags in %0.2f ms\n", (microtime(true) - $start)*1000);
~~~

The results:

![](https://dl.dropboxusercontent.com/u/449877/sharex/2015/06/2015-06-18_20-19-19.png)

If high performance is important, you'll definitely want to be pre-generating and caching the HTML output as @cebe suggested.  And if you're already doing that, sending the HTML through `strip_tags` only takes a fraction of a millisecond.  My recommendation would be to perform the `$preview = substr(strip_tags($html), 0, $limit);` call immediately after generating the HTML and cache both `$html` and `$preview` in your database.

So while I do appreciate the suggestion, I'm going to mark this as closed because the level of effort to implement `convertToText` isn't worth the 0.21ms performance benefit.

Thanks though!
