### ISSUE TITLE
Footnotes Extension?

### ISSUE THREAD

**Issue by mAAdhaTTah** [thephpleague/commonmark#242]
I'm interested in adding Footnotes support to Commonmark. Do you know if such an implementation already exists? If not, any tips on how to approach an implementation?

**Comment by colinodell** [comment]
I'm not aware of any existing implementations for this project so you'll probably need to build your own.

I'd recommend looking at how [link references](http://spec.commonmark.org/0.25/#link-reference-definitions) are implemented.  They use the `Reference` classes ([source](https://github.com/thephpleague/commonmark/tree/master/src/Reference)) to keep track of link references (which probably work similarly to how you'd implement footnotes).

Because the CommonMark spec does not cover footnotes, this feature will not be implemented directly in our core so I'm going to close this issue.  Feel free to continue the discussion though.

**Comment by ambroisemaupate** [comment]
Sorry to reply to this old post. 
Just to inform that I started a footnotes extension: https://github.com/rezozero/commonmark-ext-footnotes

Feel free to PR or suggest any improvements.

**Comment by colinodell** [comment]
This is great! I've added a link to this on our README: https://github.com/thephpleague/commonmark/commit/e773ad55d59183cf16b4e99a3807a453b1c7aed8

**Comment by nonoesp** [comment]
This is *awesome*, @ambroisemaupate. I've been waiting for this for a long time. 👌🏻

I'll try to take a look to see if I can help in any way.
