### ISSUE TITLE
Unable to find corresponding renderer for block type

### ISSUE THREAD

**Issue by sebastiaanluca** [thephpleague/commonmark#247]
Using Laravel's constructor dependency injection

```php
public function __construct(CommonMarkConverter $markdown){}
```

returns

```
RuntimeException
Unable to find corresponding renderer for block type League\CommonMark\Block\Element\Document
```

Instantiating it using the `new` keyword works, the above fails.

**Comment by jmgibson1976** [comment]
@sebastiaanluca  thats because the IoC is resolving the dependencies for CommonMarkConverter, specifically environment which is instantiated with all null properties. By instantiating it yourself without arguments, specifically the 2nd arg (Environment), the method calls Environment::createCommonMarkEnvironment(); When injected via IoC, this call never happens b/c an Environment object already exists, though all the properties are null.

You can probably resolve this by using a Laravel specific integration, though I havent tried it: https://github.com/GrahamCampbell/Laravel-Markdown

or create a class that extends CommonMarkEnvironment and inject that instead, for instance:

    class Converter extends League\CommonMark\CommonMarkConverter
    {
	public function __construct()
	{
            Parent::__construct();
        }
    }

**Comment by bennoz** [comment]
Leaving this here for the user finding this through search engines.

The recommended way is to bind the class (e.g. in `AppServiceProvider::boot`).

    $this->app->singleton(CommonMarkConverter::class, function ($app) {
        return new CommonMarkConverter();
    });
