### ISSUE TITLE
Markdown Table not working

### ISSUE THREAD

**Issue by kingRayhan** [thephpleague/commonmark#270]
Markdown table markup not working

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

**Comment by colinodell** [comment]
The [CommonMark specification](http://spec.commonmark.org/0.27/) does not support tables; because this library aims for 100% compliance, we don't support them either.

If you need this functionality, I'd recommend trying the [webuni/commonmark-table-extension](https://packagist.org/packages/webuni/commonmark-table-extension) which integrates with this library.

Discussion about adding tables to the spec can be found here: https://talk.commonmark.org/t/tables-in-pure-markdown/81

**Comment by kingRayhan** [comment]
gh
