### ISSUE TITLE
[Question]: Is there any examples for block parser?

### ISSUE THREAD

**Issue by cpdyj** [thephpleague/commonmark#297]
I didn't find any examples for the block parser in the document. And I want to know how to create a  recurse parser like this:
```
Input:
{color=red}Red**Red and Bold**{/color}
Output:
<span style='...'>Red<bold>Red and Bold</bold></span>
```
The engine provide any support for this? Or need I parse it recurse by myself?
Thank you for your help.

**Comment by colinodell** [comment]
We have some examples over at http://commonmark.thephpleague.com/customization/overview/.

If you plan on using this syntax inside of paragraphs, lists, etc then I would recommend implementing this as an Inline Parser: http://commonmark.thephpleague.com/customization/inline-parsing/  Your example will be a little more complex to implement because the inline "wraps" other inlines inside of itself - it has some starting syntax, other inlines, then closing syntax.  Because of this, you may need to also implement an Inline Processor (which I unfortunately do not have documentation for).  But if you wanted to try it, I'd recommend looking at `EmphasisParser` and `EmphasisProcessor` for some ideas on how this works.

I hope that helps!

**Comment by cpdyj** [comment]
Thank you. I will looking it.
