### ISSUE TITLE
Proper Auto Link generation (Github Style)

### ISSUE THREAD

**Issue by tankerkiller125** [thephpleague/commonmark#308]
It seems that the only way for "Auto Linking" to work is if you put corner brackets around the link which from what I can tell works, but I wouldn't consider it true auto linking. Would it be possible to use regex instead of getting the first character so that links and emails outside of corner brackets also get auto-linked (Github Style)

Possibly adding a getRegex() function to the Parser handler and allowing developers to choose between getCharacter and getRegex so they can choose which ever one works best for what their trying to do with it?

**Comment by colinodell** [comment]
Unfortunately this type of autolink is not supported by the CommonMark spec - it states that autolinks **must** be wrapped inside `<` and `>`: http://spec.commonmark.org/0.28/#autolinks.  For that reason, I do not want to include this feature in the core library here.

However, I think this would make a fantastic addition to [our commonmark-extras package](https://github.com/thephpleague/commonmark-extras)!  I've created an issue over there to track this request: https://github.com/thephpleague/commonmark-extras/issues/12  If you'd like to take a stab at implementing this you are more than welcome to do so.  Otherwise I'll give it a go sometime in the near future.

Thanks for your submission!

**Comment by tankerkiller125** [comment]
Would a getRegex function for the parser handler make sense though for future complex markdown in extensions? It seems that there's no wild card character to use in getCharacter that would allow us to check everything against a regex put in the handler.
