### ISSUE TITLE
Specify dimensions for inline images

### ISSUE THREAD

**Issue by glensc** [thephpleague/commonmark#381]
Is there way to specify dimensions for inline images, or is there css recommendation to specify max width of the images.

As the problem is that images get rendered with width:100%, which means they typically break the layout.

**Comment by glensc** [comment]
I found some existing ticket:
- https://github.com/thephpleague/commonmark/issues/309

it recommends to use https://github.com/webuni/commonmark-attributes-extension extension, is this still the recommendation?

**Comment by glensc** [comment]
so far I've adjusted CSS:

```css
#description_formatted p>img {
    max-width: 700px;
}
```

**Comment by colinodell** [comment]
If you want the ability to set different image attributes within your Markdown then https://github.com/webuni/commonmark-attributes-extension is a great choice.

Otherwise, if you're looking to apply the same attributes to all images, you should hook into the `DocumentParsedEvent` to add those attributes yourself before rendering.  Here's an example which adds a class to links (which you can adapt): https://commonmark.thephpleague.com/1.0/customization/event-dispatcher/#example  Or you could create a custom renderer instead: https://commonmark.thephpleague.com/1.0/customization/inline-rendering/#example  Either option should work for your use case.
