### ISSUE TITLE
Feature Request: Table of Contents Extension

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#441]
I've begun working on an extension that can generate a Table of Contents.  It relies on the new Heading Permalink extension, which already identifies headers and makes them linkable.  This new extension will scan for those links and build a `TableOfContents` element accordingly.

Likely configuration settings will include:

 - **How to "normalize" the ToC:**
    - Show in a tree-like structure based on the heading levels
    - Same as above, but use relative nesting levels instead of exact levels (I can't explain this very well, but I know what this means and will provide docs for it)
    - "Flatten" them into a single-level list
 - **Where to insert the ToC:**
    - Very top of the document
    - Just before the first heading
 - **Minimum and maximum heading levels to include**
    - Maybe you only want links for `h1` and `h2` elements, maybe you want them all

**Comment by GrahamCampbell** [comment]
<img src="https://cultofthepartyparrot.com/parrots/hd/parrot.gif" data-canonical-src="https://cultofthepartyparrot.com/parrots/hd/parrot.gif" width="32" height="32" />

**Comment by colinodell** [comment]
The implementation I'm working on now does indeed use a TOC element.  I think we should allow the user to select one of those two options, as they're probably the most common, but anyone could register a custom event listener that runs after ours to locate that element and move it somewhere else.

**Comment by theREALdebater** [comment]
I suggest you've got slightly the wrong idea. 
You don't want a ToC feature in the tool that converts MD to HTML. Instead you want a pre-processing tool---either a separate tool or an extension to an existing one---that sees a header named `Contents` and inserts the table of contents, as an MD bullet-list, into the MD. If there is already text following the `Contents` header, it is first deleted, so you can re-run the pre-processor whenever there have been changes to the MD file to regenerate the ToC. 
The reason why is because, to my mind, you want the ToC in the MD as well as in any transformed format (HTML, PDF, or whatever).

**Comment by colinodell** [comment]
I appreciate the feedback.  Right now, this works by inserting a `TableOfContents` node into the parsed Abstract Syntax Tree.  This `TableOfContents` node can be read, moved, deleted, etc. fairly easily.  All of this happens prior to any type of rendering, thus allowing you to implement that type of functionality.

However, I will admit that the current implementation tightly-couples the generation of the TOC with inserting it into the AST.  Perhaps we could decouple them into two classes: one responsible for generating the TOC and another responsible for adding it to the AST.  This would provide more flexibility to customize the TOC behavior to your liking.
