### ISSUE TITLE
Feature Request: Allow [TOC] to be placed manually

### ISSUE THREAD

**Issue by markcarver** [thephpleague/commonmark#459]
Currently, the ToC plugin is an all or nothing approach, meaning if enabled it's always placed that the top or before headers. There is no way to selectively add them to a document.

This is particularly problematic in Drupal filters where some content types may want TOC, but others don't. We'd have to create two separate filters/permissions just to "selectively enable" the plugin on the ones we wanted.

**Proposal**

- Add a new `manual` value for the `position` configuration
- Search for `[TOC]` prior to anything else running and replace it with a special placeholder value so it doesn't get processed by other blocks. Then replace that placeholder at the end with the ToC contents collected.

**Comment by colinodell** [comment]
Thanks for the suggestion! This has been implemented via #466

**Comment by markcarver** [comment]
Oh wow. I was looking for this issue. I didn't realize it got implemented so quickly! Awesome sauce 😄 

Is this really a 2.0 change? Any chance it can get backported to 1.x?

**Comment by colinodell** [comment]
I'm targetting it for 2.0 because I don't expect this library to need any future 1.x minor releases.  We've pushed the 1.x API to its limits and we're starting to feel some of the pain points of that.  2.x is going to:

 - Clean up a LOT of the legacy cruft
 - Fix a number of inconsistencies and poor design choices
 - Simplify custom block parsers and renderers
 - Be 35-40% faster :wink: 

For those reasons, I've been putting most of my focus into those 2.x changes.  I will consider backporting it, but I can't make any promises :stuck_out_tongue:

**Comment by markcarver** [comment]
I understand. I just have an immediate need for use on https://tag1.com where our blog authors need to use `[TOC]`, but if I enable the extension, it currently places `[TOC]` on every content type that uses markdown; not just blogs.

**Comment by colinodell** [comment]
Re-opening this for backporting into 1.5 :wink:
