### ISSUE TITLE
Consider renaming the master branch

### ISSUE THREAD

**Issue by markcarver** [thephpleague/commonmark#502]
Not that this really needs any explanation, but for posterity sake I suppose:
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by GrahamCampbell** [comment]
I'd suggest the terminology `latest`. It matches up with docker conventions, and I've been using it myself in various private repos recently (because of wanting to match branch names with docker tags).

**Comment by GrahamCampbell** [comment]
I don't think GitHub have settled on what they want to rename `master` to, out of the box, or if they are planning to make these changes to git itself, or just stuff created using the GitHub web interface.

**Comment by markcarver** [comment]
Ooh, I do like `latest` as well 😄 

I was merely going after what the article and many others have suggested.

Also, a co-worker of mine mentioned the following that made sense to me too:

> I'm probably going to be using `main` in a lot of my projects just for the muscle memory of `git pull origin ma<tab>`

**Comment by colinodell** [comment]
I am fully in favor of renaming that branch to something else.  I'm also really bad at naming things. 
 Ideally we'd pick something that matches a common convention - I don't care what the word is, as long as it's universally understood.  I see the merits of both `main` and `latest` but it's not clear to me which will "win out" in the coming months.  I also don't want to wait on this change unnecessarily.

**Perhaps we could rename it to `2.0` for now since that's exactly what it contains?**  It would match up with the other branch names we use now and would eliminate the need for the branch alias in `composer.json`.  And because 2.0.0 likely won't be released for 2-3 months that gives us some time to see what direction the broader community goes in before we have to spin off a new branch for whatever might contain post-2.0.0 changes.

**Comment by markcarver** [comment]
I'm in favor of renaming it `2.0`.

**Comment by GrahamCampbell** [comment]
Yep, 2.0 is a great name.

**Comment by GrahamCampbell** [comment]
No need for branch aliases in the compiser.json then, at all. Branch aliases were only a work around to enable naming the 2.0 branch master... kind counter intuitive with hindsight :P Just name it 2.0. ;)

**Comment by colinodell** [comment]
On second thought... we have a lot of things like badges and CI jobs and changelog links which all point to the most-recent branch.  Those are going to be a hassle to change with each new major/minor release.  For that reason, let's go with `latest` instead :upside_down_face:

**Comment by markcarver** [comment]
wfm

**Comment by colinodell** [comment]
This has been completed:

![image](https://user-images.githubusercontent.com/202034/84841785-57ab5400-b011-11ea-9051-96669b45a7f1.png)

We shall use `latest` moving forward.

**Comment by glensc** [comment]
> I'd suggest the terminology `latest`. It matches up with docker conventions, and I've been using it myself in various private repos recently (because of wanting to match branch names with docker tags).

Just that docker terminology for 'latest' equivalent in git would be a moving tag, not a branch.

also, as 2.x is not out there, so 1.x is still maintained, "latest" would create real confusion when 2.x branch is behind 1.x branch on the next 1.x release, say 1.5.5

refs:
- https://github.com/thephpleague/commonmark/issues/432#issuecomment-796033712
