### ISSUE TITLE
Question: how do I prevent a core block parser being used/registered in 1.5.4?

### ISSUE THREAD

**Issue by Ambient-Impact** [thephpleague/commonmark#536]
Hi there. I'm in need of disabling the indented code parser for a project that I'm working on. We don't need code blocks, and it would be easier for our content authors to not have to worry about indenting, as that can be useful for readability. As far as I can tell, I would need to duplicate all of ```League\CommonMark\Extension\CommonMarkCoreExtension::register()``` to remove that, or else create a custom environment class with a hacky ```addBlockParser()``` method to ignore the ```IndentedCodeParser``` class. Is there some easier and future proof way of doing this that I'm missing?

**Comment by colinodell** [comment]
A method to easily remove parsers is unfortunately not available in 1.x and probably can't be added without breaking backward compatibility.  That being said, I'm not opposed to adding this feature to 2.x if that would be useful for you.

**Comment by Ambient-Impact** [comment]
@colinodell Such a feature would indeed be useful in the future!

In the meanwhile, I've come up a workaround: I've created a custom block element/parser/renderer that's weighted one less than the ```IndentedCode``` parser and which simply moves the cursor past the indentation before passing parsing off, thus preventing the ```IndentedCode``` from matching. I'll share it in case anyone else has a need for this, but this is specific to the indenting issue, so it won't help with other types of parsers.

(Don't forget to replace ```<your namespace>``` with your actual namespace. 🤓)

```<your namespace>\CommonMark\Block\Element\IndentedContent.php```:
```php
<?php

namespace <your namespace>\CommonMark\Block\Element;

use League\CommonMark\Block\Element\AbstractBlock;
use League\CommonMark\Cursor;

/**
 * Indented content CommonMark element.
 */
class IndentedContent extends AbstractBlock {

  /**
   * {@inheritdoc}
   */
  public function canContain(AbstractBlock $block): bool {
    return true;
  }

  /**
   * {@inheritdoc}
   */
  public function isCode(): bool {
    return false;
  }

  /**
   * {@inheritdoc}
   */
  public function matchesNextLine(Cursor $cursor): bool {
    // If this is indented, just advance the cursor and return true, thus
    // allowing normal parsing to continue rather than be detected as an
    // indented code block.
    if ($cursor->isIndented()) {
      $cursor->advanceToNextNonSpaceOrTab();

      return true;
    }

    return false;
  }

}
```

```<your namespace>\CommonMark\Block\Parser\IndentedContentParser.php```:
```php
<?php

namespace <your namespace>\CommonMark\Block\Parser;

use <your namespace>\CommonMark\Block\Element\IndentedContent;
use League\CommonMark\Block\Parser\BlockParserInterface;
use League\CommonMark\Block\Element\Paragraph;
use League\CommonMark\ContextInterface;
use League\CommonMark\Cursor;

/**
 * Indented content CommonMark parser.
 */
class IndentedContentParser implements BlockParserInterface {

  /**
   * {@inheritdoc}
   *
   * @see \League\CommonMark\Block\Parser\IndentedCodeParser::parse()
   *   Identical to this method other than the block added at the end, i.e.
   *   new IndentedCode() -> new IndentedContent()
   */
  public function parse(ContextInterface $context, Cursor $cursor): bool {
    if (!$cursor->isIndented()) {
      return false;
    }

    if ($context->getTip() instanceof Paragraph) {
      return false;
    }

    if ($cursor->isBlank()) {
      return false;
    }

    $cursor->advanceBy(Cursor::INDENT_LEVEL, true);
    $context->addBlock(new IndentedContent());

    return true;
  }

}
```

```<your namespace>\CommonMark\Block\Renderer\IndentedContentRenderer.php```:
```php
<?php

namespace <your namespace>\CommonMark\Block\Renderer;

use League\CommonMark\Block\Element\AbstractBlock;
use League\CommonMark\Block\Renderer\BlockRendererInterface;
use League\CommonMark\ElementRendererInterface;

/**
 * Indented content CommonMark renderer.
 */
class IndentedContentRenderer implements BlockRendererInterface {

  /**
   * {@inheritdoc}
   */
  public function render(
    AbstractBlock $block,
    ElementRendererInterface $htmlRenderer,
    bool $inTightList = false
  ) {
    // This just renders the children in place, without a containing element.
    //
    // @todo Can we return a \League\CommonMark\HtmlElement like the
    //   documentation recommends as a best practice? How do we do that without
    //   an element/tag name?
    return $htmlRenderer->renderBlocks($block->children());
  }

}
```

And you would add it like so:
```php
use League\CommonMark\Environment;
use <your namespace>\CommonMark\Block\Element\IndentedContent;
use <your namespace>\CommonMark\Block\Parser\IndentedContentParser;
use <your namespace>\CommonMark\Block\Renderer\IndentedContentRenderer;

...

/** @var \League\CommonMark\ConfigurableEnvironmentInterface */
$environment = Environment::createCommonMarkEnvironment();

// This adds our IndentedContentParser class one weight lighter than
// \League\CommonMark\Block\Parser\IndentedCodeParser so that we can render
// indented content before the latter parser gets to it, thus preventing it from
// matching.
//
// @see \League\CommonMark\Extension\CommonMarkCoreExtension::register()
//   Default CommonMark parsers added here.
$environment->addBlockParser(new IndentedContentParser(), -99);

// This adds our IndentedContentRenderer as the renderer for our IndentedContent
// element.
//
// @see \League\CommonMark\Extension\CommonMarkCoreExtension::register()
//   Default CommonMark parsers added here.
$environment->addBlockRenderer(
  IndentedContent::class, new IndentedContentRenderer()
);
```

**Comment by markcarver** [comment]
IMO, this library already has the ability to completely customize the environment. `CommonMarkCoreExtension` is just a convenience "extension" to register the spec-compliant CommonMark parsers/renderers. If someone wishes to deviate from this, then they can easily create their own (literally just copy & paste and then comment/replace what you want).

I don't really see the benefit of "removing" already registered extensions; the environment should be built correctly from the beginning. Anything else is advanced customization.

---

Also, given that the OP has already solved their specific issue by using their own weighted parser/renderer seems like this issue is ultimately moot as that is the purpose of the weights.

**Comment by Ambient-Impact** [comment]
Could there be instances where weights alone can't solve an issue with a certain parser/renderer? It feels to me like copying the entire ```CommonMarkCoreExtension``` just to remove one parser is overkill.

**Comment by markcarver** [comment]
> Could there be instances where weights alone can't solve an issue with a certain parser/renderer?

Unlikely. This topic in general is already fairly edge-case.

> It feels to me like copying the entire `CommonMarkCoreExtension` just to remove one parser is overkill.

This is by design. The reason this extension is included by default is that its the core functionality of the CommonMark spec (what this library is designed to do). Removing one of these is likely to have unforeseen consequences unless you really know what you're doing. The best approach is what you've already discovered above by using custom extensions and weights to intercept your desired functionality prior to the core functionality.

That is why the documentation indicates this kind of customization is [Manual Usage](https://commonmark.thephpleague.com/1.5/extensions/commonmark/#manual-usage):
> <p>Alternatively, if you don’t want all of the core Markdown syntax, avoid using <code class="language-plaintext highlighter-rouge">CommonMarkCoreExtension</code>. You can always add just the individual parsers, renderers, etc. you actually want with the <a href="/1.5/customization/environment/"><code class="language-plaintext highlighter-rouge">Environment</code></a>. (This is actually how the <a href="/1.5/extensions/inlines-only/">Inlines Only Extension</a> works - it only includes a subset of things that <code class="language-plaintext highlighter-rouge">CommonMarkCoreExtension</code> does!)</p>

**Comment by colinodell** [comment]
The biggest challenge with allowing things to be removed from the environment is that some extensions (like the Mention extension) register multiple parsers using the same class and it wouldn't be easy to pinpoint specific ones for removal.  I do think it's more straight-forward to require developers to only add what they need instead of allowing both adding and removing things.

That being said, if there is an edge case that can't be solved using any of the built-in features and removing certain parsers/renderers is the only solution, I would be open to considering that specific case.  But I do have to agree with @markcarver here, there are at least two ways to solve this presently, so I don't think this feature would provide many benefits at the moment (weighing the usefulness against the complexity and other options).

**Comment by Ambient-Impact** [comment]
Fair enough, thanks!

**Comment by bplace** [comment]
Thank you for sharing this, works like a charm with Blade templates.

**Comment by Ambient-Impact** [comment]
@bplace Always happy to help others who run into the same issues!
