### ISSUE TITLE
Question: Custom HTML Tags and Safety

### ISSUE THREAD

**Issue by mustafa519** [thephpleague/commonmark#538]
## Question

I've checked out all documentation and all source codes. But still i couldn't find out the way to implement my custom tags. The library seems flexible enough to implement that but i'm really confused about my custom implementation.

Could you suggest an example to define and use our custom tags?

**I need to implement something like that:**

```html
<blocks>
  <block align="center" another-custom-attr="hi">
    **bold text**
  </block>
</blocks>

<!-- Output: entirely same output and no parsed content even paragraph tho -->
<blocks>
  <block align="center" another-custom-attr="hi">
    **bold text**
  </block>
</blocks>
```

**Also this works properly:**

```html
<blocks><block>**bold text**</block></blocks>

<!-- Output: <p><blocks><block><strong>bold text</strong></block></blocks></p> -->
```

**Also;**
- I couldn't understand much the difference between parser and renderer. There is no enough information and real use case examples on the documentation.
- How can i prevent to encode for custom tags?
- How can i check the custom attributes of custom elements?
- Do i need to use any other filter library to sanitize safe output? Like [tgalopin/html-sanitizer](https://github.com/tgalopin/html-sanitizer) And when we need to careful about output.

Version: `1.5`

Thanks,
Mustafa

**Comment by colinodell** [comment]
Hi Mustafa,

> I couldn't understand much the difference between parser and renderer.

Here's a simplified version of how this library works (as far as your use case in concerned) - converting Markdown to HTML has three main steps:

1. [Parse the Markdown text](https://commonmark.thephpleague.com/1.5/customization/overview/#add-custom-syntax-with-parsers) to understand what types of markup it contains - we call this object representation [the "AST"](https://commonmark.thephpleague.com/1.5/customization/event-dispatcher/#list-of-available-events)
2. [Dispatch an event](https://commonmark.thephpleague.com/1.5/customization/event-dispatcher/#list-of-available-events) to let code view and modify the AST if needed
3. Iterate through the AST and [render](https://commonmark.thephpleague.com/1.5/customization/overview/#customize-html-output-with-custom-renderers) those objects as HTML

By default, this library will always parse all of the HTML content it finds in your Markdown and create `HtmlBlock` and `HtmlInline` objects in the AST.

> How can i prevent to encode for custom tags?

The encoding/escaping is done by the two renderers responsible for rendering the `HtmlBlock` and `HtmlInline` objects:

 - https://github.com/thephpleague/commonmark/blob/1.5.4/src/Block/Renderer/HtmlBlockRenderer.php
 - https://github.com/thephpleague/commonmark/blob/1.5.4/src/Inline/Renderer/HtmlInlineRenderer.php

They only support [three options by default](https://commonmark.thephpleague.com/1.5/security/#html-input), none of which allow you to specify certain HTML elements that are or aren't allowed by default - it's all or nothing.

There is an extension (which is part of GFM) that does allow certain tags to be escaped: https://github.com/thephpleague/commonmark/tree/1.5.4/src/Extension/DisallowedRawHtml  You could potentially use that kind of approach if you'd like.

Alternatively, you could create some kind of event listener that looks for HTML elements in the AST and converts any you want to keep into some other type of custom AST element.  This would be more complex to implement, but it would allow your custom syntax to be handled completely differently from HTML.

> How can i check the custom attributes of custom elements?

This library does not provide any way to do this, because Markdown syntax doesn't care what the HTML contains - we only need to know whether or not something is HTML and whether it should be escaped.  Parsing custom attributes within HTML would be your responsibility.

> Do i need to use any other filter library to sanitize safe output? Like tgalopin/html-sanitizer And when we need to careful about output.

Yes, but only if you need to allow some HTML tags and not others.

> There is no enough information and real use case examples on the documentation.

I apologize, it's very hard to write documentation and I don't always have enough time to write as much as I'd like. Contributions are always welcome though!

**Comment by mustafa519** [comment]
I've already preferred to customize the `DisallowedRawHtml` extension before. But i couldn't, because the parser doesn't parse inside of the block HTML element.

It looks that the best and fast way is to use the another filter library to intended safe sand customized output.

Is there any shortcut which lets Markdown parser to parse inside of the custom block HTML tags? Because the below example doesn't work even though I've allowed all HTML input. It allows to generate HTML output but Markdown Parser doesn't parse inside of tags.

```html
<blocks>
  <block align="center">
    | Tables        | Are           | Cool  |
    | ------------- |:-------------:| -----:|
    | col 3 is      | right-aligned | $1600 |
    | col 2 is      | centered      |   $12 |
    | zebra stripes | are neat      |    $1 |
  </block>
  <block>
    ## Example Heading
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse, nihil?
  </block>
</blocks>
```

**My Configuration Options:**

```php
$converter = new CommonMarkConverter(
  [
    'html_input' => 'allow',
    'allow_unsafe_links' => true,
    'max_nesting_level' => 3,
    ...
```

And thank you for the detailed explanation and fast response. I'm waiting for `v2.0` to adaptive the library deeply. And when I have enough time, I'll support the amazing library as much as I can.

**Comment by markcarver** [comment]
https://commonmark.thephpleague.com/1.5/security/#additional-filtering:

> ### Additional Filtering
> Although this library does offer these security features out-of-the-box, some users may opt to also run the HTML output through additional filtering layers (like HTMLPurifier). If you do this, make sure you thoroughly test your additional post-processing steps and configure them to work properly with the types of HTML elements and attributes that converted Markdown might produce, otherwise, you may end up with weird behavior like missing images, broken links, mismatched HTML tags, etc.


---


IMO, this isn't really an issue with this library. It really boils down to the use of "custom HTML" mixed with Markdown. In CMSes (like Drupal), this can be quite a common occurrence (especially when using advanced FE features like web components or libraries like React or Vue).

In advanced use cases like this (where you need more control over custom elements), it's best to entirely disable this library's sanitization (`'html_input' => 'allow'` and `'allow_unsafe_links' => true`) and then filter/sanitize undesirable HTML afterward using some sort of 3rd party library (Drupal has APIs for XSS filtering built-in).
