### ISSUE TITLE
Something analogous to HtmlRenderer's renderInlines() for parsing?

### ISSUE THREAD

**Issue by melyuksel** [thephpleague/commonmark#54]
Say you're doing some custom inline parsing, and want a certain character to put the rest of the line into a span.

```
This is :some text here\n
Such :wonderful text
````

would become

```HTML
This is <span>some text here</span>
Such <span>wonderful text</span>
````

This could (presumably) be done with the Processor interface, but that seems like a pretty complex beast and would require a separate class to match every single newline or end of line.

Instead, one could in theory just simply use something similar to what ````htmlRenderer->renderInlines()```` during rendering, and just advance over the rest of the line while saving it to string and doing some sort of ````parse()```` over it separately. However, there is no way to access the mother Environment object to see what the rules are.

I've "solved" this by doing something like this:

````PHP
public function parse(ContextInterface $context, InlineParserContext $inlineContext)
{
        . . .

        $remainder = $cursor->match('/.*(?=$|\n)/'); // Match everything before newline, or end of line
        
        $newInlineCursor = new Cursor($remainder);
        require 'CommonMarkEnvironment.php'; // Contains $environment declaration and rules
        $newInlineParserEngine = new InlineParserEngine($environment);
        $newInlines = $newInlineParserEngine->parse($context, $newInlineCursor)->toArray();
		
        $inlineContext->getInlines()->add(new Indent($newInlines)); // Indent extends AbstractInlineContainer

        return true;
}
````

But this is obviously very dirty since it involves calling the code that established the current Environment again and creating a whole new Environment instance. Is there already a way to just simply have a certain string parsed as inlines according to the existing mother Environment rules?

One way that would work pretty great is if the Context class had a ````getEnvironment()```` method in the same way that it has a ````getDocument()```` method, since its constructor accepts both a Document and and an Environment object, but only has a getter method to retrieve the Document and not the Environment.

**Comment by colinodell** [comment]
I understand why you "solved" the problem in that manner, but that approach likely breaks emphasis and link parsing because your new `InlineParserEngine` won't contain the current inlines or delimiter stack.  For example, if you were to parse this:

~~~markdown
This is a **test: hello!**
~~~

You'd likely end up with HTML like this:

~~~html
This is a **test<span> hello!**</span>
~~~

Because your newly-created inline parser engine would "consume" the ending `**` characters into its internal inline context which the outer parser engine doesn't know about.

> This could (presumably) be done with the Processor interface

Yep that's correct.  In this case, since there's no ending character, your best bet would be using the delimiter stack with a custom processor to handle the not-yet-identified inlines.

You'll want to create a custom which stops at `:` characters and pops them onto the delimiter stack:

~~~php
class SpanParser extends AbstractInlineParser
{
    public function getCharacters()
    {
        return array(':');
    }

    public function parse(ContextInterface $context, InlineParserContext $inlineContext)
    {
        if ($inlineContext->getCursor()->getCharacter() !== ':') {
            return false;
        }

        $inlineContext->getCursor()->advance();
        // Insert a Text element for now; this will likely get replaced with a Span element later
        $inlineContext->getInlines()->add(new Text(':', array('delim' => true)));

        // Add entry to stack for this opener
        $delimiter = new Delimiter(':', 1, $inlineContext->getInlines()->count() - 1, true, false, $cursor->getPosition());
        $inlineContext->getDelimiterStack()->push($delimiter);

        return true;
    }
}
~~~

The existing `InlineParserEngine` would continue parsing anything else after the `:`.  Once that's done, it'll call any inline processors which might be interested in modifying the parsed inlines.  In our case, we want to locate the `:` delimiter(s), obtain all the inlines which occurred after it, and stuff those inside a custom `Span` element:

~~~php
class Span extends AbstractInlineContainer
{
}

class SpanProcessor implements InlineProcessorInterface
{
    public function processInlines(ArrayCollection $inlines, DelimiterStack $delimiterStack, Delimiter $stackBottom = null)
    {
        $delim = $delimiterStack->searchByCharacter(':');
        if ($delim->getChar() === ':') {
            $span = new Span($inlines->splice($delim->getPos()));
        }
    }
}
~~~

I haven't actually tested that code, so there's probably a bug or two in there, but that overall strategy should work.

I'm going to mark this issue as closed for now (since exposing the Environment is unnecessary for this purpose) but feel free to continue discussion, and we can always re-open it if needed.

**Comment by melyuksel** [comment]
While I can see why you'd be cautious to expose the Environment, the parser would of course be cautious enough to make sure that a regular grammatical colon would not be confused for the CommonMark operator. Even if it was, adjusting precedence of the rules can fix any potential nesting problems. So it wouldn't matter if the new parser consumed any delimiters.

Nevertheless, yours is the clean "way", but on the contrary, there IS an ending character, which can be either a \n or the end of the string. I don't think it's possible to even match the end of the string with getCharacters().

**Comment by colinodell** [comment]
> Even if it was, adjusting precedence of the rules can fix any potential nesting problems. So it wouldn't matter if the new parser consumed any delimiters.

Are you sure?  Each new `InlineParserEngine` instance creates its own inline context which is where the inlines and delimiters are tracked.  So, given the example string of `This is a **test: hello!**`, here's what the main parser's context will contain immediately prior to parsing the colon:

* Delimiter stack:
    * `**`, pos = 1
* Inlines:
    * 0 => Text: `This is a `
    * 1 => Text: `**`, delim = true
    * 2 => Text: `test`

When you create the new parser and parse the remaining content, your new parser engine will have this within it's context:

* Delimiter stack:
    * `**`, pos = 1
* Inlines:
    * 0 => Text: ` hello!`
    * 1 => Text: `**`, delim = true

When it runs the processors, your `$newInlineParserEngine` will only find a single `**` delimiter and therefore won't create the inline emphasis.

The outer ("main") inline parser has it's own context with a single `**` delimiter too, and therefore it'll render the `**` as-is since there's no closing delimiter.

> I'm not sure whether it's possible to even match the end of the string with getCharacters().

Nope, you cannot, and you probably wouldn't since your syntax doesn't use a closing delimiter.  This is another reason why you'd need to use a processor, since it runs after the whole string has been parsed.

> My point still stands though, where I think it would be a good idea to have a way to parse any given string based on the already established Environment's rules, without having to expose the Environment.

I understand your concern, but I think the current structure is sufficient for all the use-cases we've seen so far.  I'd be very hesitant to expose the Environment here, thus enabling users to work outside of the established methodology.

**Comment by melyuksel** [comment]
That's fair, and one can always modify the code themselves to fit their needs if they absolutely need to anyway. In practice, I actually intended and mandated that the colon only apply when it was the first character of the line, which would eliminate these issues with the Delimiter.

If two properly registered processors, though, had a conflict over nesting in a case, would the Delimiter stack not end up like this anyway? Say * and % are both delimiters for separate processors, and come upon a text like ````*Jack and Jill %were walking* in the park%````, would this not still create the same conflict you mentioned?

One question in the way of implementing my parser: my syntax DOES use a closing delimiter (a newline) or none at all if it hits the end of the string before a newline occurs. Is there a way I could use a Processor to handle this case?
