### ISSUE TITLE
Question: Strip content based on regex

### ISSUE THREAD

**Issue by faustbrian** [thephpleague/commonmark#545]
Is there an easy way to stripe out content based on regular expressions? My use-case would be to strip out FrontMatter blocks with a regex like `/^---[.\r\n]*---/` but an extension seems overkill for that or would a parser extension be the recommended way to solve this?

**Comment by colinodell** [comment]
We recently implemented a FrontMatter extension via #532 which seems to do exactly what you're looking for :)  It hooks into the `DocumentPreParsedEvent` to remove the front matter from the markdown.

I do think that implementation might be a little overkill due to https://github.com/thephpleague/commonmark/issues/442#issuecomment-691499981 but I'm not sure if I want to keep it as-is or partially revert/change the feature yet, since I don't think the benefits outweigh the breaking changes :-/

**Comment by colinodell** [comment]
I keep going back and forth on whether to revert #532.  If we do keep it, then you can use that extension as-is to strip the front matter blocks or listen to the `DocumentPreParsedEvent` event to strip content yourself.  Otherwise, if #532 is reverted, that will mean the preferred approach is to strip it yourself before passing it into the converter.  Either way what you're looking to do is possible, so I'm going to close this issue.
