### ISSUE TITLE
HTML with blank lines gets turned into code

### ISSUE THREAD

**Issue by faustbrian** [thephpleague/commonmark#548]
**Version(s) affected**: 1.5.5

**Description**  

```
<div class="mt-5 alert-wrapper danger">
    <div class="alert-icon-wrapper danger-icon">
        ...
    </div>

    <div class="alert-content-wrapper danger-content">
        <span class="danger-title"></span>
        <span class="block">hi</span>
    </div>
</div>
```

Given this block of HTML, you will receive an output that is half unmodified and half turned into a `pre` block. Using BabelMark There are differing outputs	

```
<div class="mt-5 alert-wrapper danger">
  <div class="alert-icon-wrapper danger-icon">
    ...
  </div>
  

<pre>
    <code>&lt;div class="alert-content-wrapper danger-content">
    &lt;span class="danger-title">&lt;/span>
    &lt;span class="block">hi&lt;/span>
&lt;/div>
</code>
  </pre>
</div>
```

Looking at BabelMark it seems to be the expected behaviour since packages that do this are marked as CommonMark Compliant. Is there any way to alter this behaviour? The part that generates this HTML blob is out of my control so I can't do anything to it before it is included in the markdown.

**How to reproduce**  

https://babelmark.github.io/?text=%3Cdiv+class%3D%22mt-5+alert-wrapper+danger%22%3E%0A++++%3Cdiv+class%3D%22alert-icon-wrapper+danger-icon%22%3E%0A++++++++...%0A++++%3C%2Fdiv%3E%0A%0A++++%3Cdiv+class%3D%22alert-content-wrapper+danger-content%22%3E%0A++++++++%3Cspan+class%3D%22danger-title%22%3E%3C%2Fspan%3E%0A++++++++%3Cspan+class%3D%22block%22%3Ehi%3C%2Fspan%3E%0A++++%3C%2Fdiv%3E%0A%3C%2Fdiv%3E

**Comment by colinodell** [comment]
Yep you are correct that this is the intended behavior of the spec as illustrated by this example: https://spec.commonmark.org/0.29/#example-118

I don't think there's an easy, reliable way to change this behavior because the parser doesn't see the full content ahead of time.  For example, after it's parsed this part:

```
<div class="mt-5 alert-wrapper danger">
    <div class="alert-icon-wrapper danger-icon">
        ...
    </div>
```

All it sees next is an empty line - it cannot see further ahead than that.  We _might_ have some additional HTML after that, or we might not - we simply have no way to know.  This is a major reason why CommonMark has adopted that rule.

You could try tinkering around with bits of code like https://github.com/thephpleague/commonmark/blob/1.5/src/Block/Element/HtmlBlock.php#L75 which is what currently determines if the next line is part of that HTML block, but there's a good chance you may end up with unexpected results.

An alternative idea would be pre-processing your Markdown input with something that fully understands HTML and strips out blank lines from within open blocks - passing that into CommonMark would then give you the desired results.

**Comment by faustbrian** [comment]
Ended up going with pre-processing it, bit hacky due to how it is retrieved but resolved it.
