### ISSUE TITLE
Remove unnecessary `prefix` configuration from mentions

### ISSUE THREAD

**Issue by markcarver** [thephpleague/commonmark#567]
https://github.com/thephpleague/commonmark/pull/560/files#r499779399

Now that the inline parser can handle full regex and subgroup matches, there's no real need to keep these separated; it should live inside the `regex` configuration of the mention.

**Comment by colinodell** [comment]
You're right that we don't technically need prefixes, but there are 3 small benefits to keeping the `prefix`:

1. The user doesn't have to remember to add the capturing group parens themselves, making the upgrade path slightly easier
2. No need to validate for the presence of the capturing group at runtime since we're always guaranteed to have it if the engine is the one adding it.
3. We might find a way to further optimize the inline parser when matching against regular expressions with a fixed starting string. Under the current implementation, we could change `getMatchDefinition()` to return just the prefix and take advantage of such an optimization without requiring a BC-break.

Granted, that third benefit is an unknown/unproven one that might never happen, but I do like having the option to optimize it in a minor version if we find that it's necessary.

That being said, the mention extension is your baby and if you feel like prefixes truly aren't needed anymore and you're comfortable with the small (but real) potential downsides then I'd be open to dropping it after taking a quick look to ensure performance is as good as we can reasonably get it.  I'm just hesitant to lock us out of potential future optimizations if we can avoid it :)

**Comment by markcarver** [comment]
Hm. I guess I'm being a little overzealous here.
