### ISSUE TITLE
Question: Is there a way to remove markdown syntax ?

### ISSUE THREAD

**Issue by Bacteries** [thephpleague/commonmark#610]
Hi,
I use Commonmark and it works well but I have a case where I need to display my text on a non HTML output.
Is there a way to take the markdow text and return the text without  the Markdown ? (and keep list "-") ?

I know something like this could works, but I was searching for the proper way (extension maybe ?) to do this, and if one already exists.
```
$string = str_replace(['<li>'], ['- '], $htmlFromMarkdown);
return strip_tags($string);
```
Thanks.

**Comment by colinodell** [comment]
You could implement [custom block renderers](https://commonmark.thephpleague.com/1.5/customization/block-rendering/) and [inline renderers](https://commonmark.thephpleague.com/1.5/customization/inline-rendering/).  Although they are intended to output HTML there's nothing stopping you from returning any text strings that you want :)

You could then group those renderers into an extension or add them manually to the `Environment` - both will accomplish the same thing.  Just make sure you set a higher priority so that your renderers are used instead of the core ones.

**Comment by Bacteries** [comment]
Hi @colinodell : I make my own renderers and it works fine ! Thanks.
