### ISSUE TITLE
Feature Request: Custom widget rendering using placeholder system

### ISSUE THREAD

**Issue by armetiz** [thephpleague/commonmark#626]
Based on table of contents `position=placeholder` system, I want to be able to add custom "widget".

Example:

```php
$environment = new CommonMark\Environment\Environment([
    'widgets' => [
        [
            'content' => '<span>This is an example</span>',
            'placeholder' => '[EXAMPLE]',
        ],
        [
            'content' => static function() {
                return '<span>This is an other example</span>';
            },
            'placeholder' => '[EXAMPLE_BIS]',
        ],
    ],
]);
```

Markdown content.

```markdown
Some content
Some content
[EXAMPLE]
Some content
[EXAMPLE_BIS]
Some content
[EXAMPLE]
Some content
Some content
```

HTML 

```html
<p>Some content</p>
<p>Some content</p>
<span>This is an example<span>
<p>Some content</p>
<span>This is an example<span>
<p>Some content</p>
<span>This is an other example<span>
```
Regards.

Thomas.

**Comment by colinodell** [comment]
Thanks for sharing the idea!  I do have a few questions to help me better understand what you're looking for:

 - Would you mind sharing some specific, real-world examples of how you might use this?
 - If `content` is a function, what parameters (if any) would be passed in?
 - Would these widgets be considered blocks, inlines, or is it really more of a find-and-replace feature?

**Comment by armetiz** [comment]
Within content, I want to place an auto-promo banner. The banner's content will be dynamic. Technical, the banner content will be generated using Twig engine.
I do not have real world example for the function usage. I copied one of your component configuration.

**Comment by markhalliwell** [comment]
Per #630, I think this use case could also be served by the [Mentions Extension](https://commonmark.thephpleague.com/extensions/mentions).

**Comment by colinodell** [comment]
I can definitely see how this feature could be useful, but I'm struggling to determine exactly how to best implement this.  The challenge is not necessarily technical, but rather how to create a useful extension that is generic enough to fit everyone's needs.

Some of the questions we'd need to figure out are:

### Syntax

What should the syntax be?  Your proposal might be fine, but it's also the same syntax as [short reference links](https://spec.commonmark.org/0.30/#shortcut-reference-link); if we want to use that anyway, how do we handle conflicts? Which takes priority?

Is there an alternative syntax that works better? One that other Markdown parsers use?

### Replacement Procedure

When should placeholders be replaced?  Should it happen prior to parsing, so that placeholder can use Markdown?  Should it work like the [Table of Contents](https://commonmark.thephpleague.com/2.0/extensions/table-of-contents/) placeholder, where we have an actual AST node for it?

### Content Generation

Users will want the ability to generate content dynamically using functions that might query a database, load a file, call an API, etc.  What parameters would that function need?  Should that function have the ability to indicate that no content should be rendered?  The behavior of that API needs to be determined.

### Use Cases

Users will want to do different things with this extension.  Some may want to drop in hard-coded HTML for ads, others may want to inject CMS blocks, and I'm sure there are other situations where users want to do things.  Understanding these use cases will help us determine how to best support them.
----

So while I think this is a good idea, I'm hesitant to start implementing something without having a better idea of the ideal approach.  I also think it's possible that a one-size-fits-all solution might be too vague, and perhaps users might be better off implementing their own custom solution perfectly tailored to their needs.

Any feedback that anyone has would be greatly appreciated here!

**Comment by samwilson** [comment]
Is this still a valid proposal? (I assume it's closed as stale, not as declined.) I've been looking for something like this, similar to WordPress [shortcodes](https://codex.wordpress.org/Shortcode) or MediaWiki [templates](https://www.mediawiki.org/wiki/Help:Templates).

For example this config

```php
$environment = new CommonMark\Environment\Environment([
    'widgets' => [
        'foo' => function ($attrs) {
            return '(This is foo with first attr ' . $attrs['attr1'] . ')';
        },
    ],
]);
```

and this Mardown

```
lorem {foo attr1=bar attr2="baz bif"} ipsum
```

would result in

```
lorem (This is foo with first attr bar) ipsum
```

Of course the syntax is the tricky bit. I think square brackets are already used lots, and curly braces match what MediaWiki does. There is lots of discussion about this sort of thing at https://talk.commonmark.org/t/generic-directives-plugins-syntax/444
