### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by mt3o** [thephpleague/commonmark#63]
I found error while parsing some markdown with ul/li. 
I think it might be commonmark error. 

Here is right version:
http://jbt.github.io/markdown-editor/#XVJtjtNADP2fU1haCQEqe4eKUm0kVlqqSoif0xk3MTsZB3tC6W04CyfDM2m3H7/iebafn5/TPMBm2X79vvwB77fiBl2ATruDO1rQU9eDjogBIiVU+ABt2ovTLJPPk2DTrIUHGAU/jcI/0WfIDIOjlDG55HEBz8tVu15Dj3FUoAw+EqZsYYLcIwT8jZHHwTDgfYFI4MSlsGcB4WjDO9DM/tXEUZdcBD1qxkHBpQDiKBrftTB9hM27Vc2ehQ0uuQ7LoKZpPv77u6KOsosl3AqmUIIXuS81cEP6Wr7fJhcpH2+IHuBFONhMkzcFQq3Un53AjsMR1NaOjwX6Eo1YyF+kV7g1o4Rsy6IU/5wee8rZVp5LbMA4RSVON51XhLW3PnlA37tUUfw1UfX1PMnMHFy+51ndHqB3Eg5OcDHnituV33OazS395VCoGXaYfI96LcBmgzcOI5/N8ah6Y87zReKlrzxL8smgcu0qbTllPimuZ+YdZ/Kz7C3zW11r0lyMc+WAuedw3jlMpprsbnrafBZy7+CBpPxib73/AQ==

**Comment by colinodell** [comment]
The Markdown you provided renders itself like this:

~~~html
<h1>RAILWAY (Trams, subways, high speed lines ) Infrastructure</h1>
<p>From pre-project to maintenance, MADIFF helps it clients in the development of their projects for rolling stock, signal systems and rail infrastructures. R&amp;D and project management</p>
<p>* Digital
* Trend
* Prject management
* Risk
* Quality management</p>
<h1>Product studies</h1>
<p>* Car body shell.
* Electrical systems.
* Interior and exterior fittings.
* Propulsion systems.
* Electrical and electromechanical equipments.
* Information systems.
* Development of hardware,
* Design and construction of test benches and electronic cards.</p>
<h1>Process studies</h1>
<p>* Mechanical and electrical
* Handling.
* Automation and robotics.
* Tooling.
* Installation methods.
* Industrialisation studies.
* Electrical wiring methods.</p>
~~~

This occurs because you're using a **non-breaking space** (U+00A0) after the `*` character, whereas [the CommonMark spec requires a **normal** space](http://spec.commonmark.org/0.17/#list-items) (U+0020).  You'll see the same exact behavior if you [feed the sample input into the JS dingus](http://spec.commonmark.org/dingus.html?text=%0A%23%20RAILWAY%20(Trams%2C%20subways%2C%20high%20speed%20lines%20)%20Infrastructure%0A%0AFrom%20pre-project%20to%20maintenance%2C%20MADIFF%20helps%20it%20clients%20in%20the%20development%20of%20their%20projects%20for%20rolling%20stock%2C%20signal%20systems%20and%20rail%20infrastructures.%20R%26D%20and%20project%20management%0A%0A%0A*%C2%A0Digital%0A*%C2%A0Trend%0A*%C2%A0Prject%20management%0A*%C2%A0Risk%0A*%C2%A0Quality%20management%0A%0A%23%20Product%20studies%0A%0A*%C2%A0Car%20body%20shell.%0A*%C2%A0Electrical%20systems.%0A*%C2%A0Interior%20and%20exterior%20fittings.%0A*%C2%A0Propulsion%20systems.%0A*%C2%A0Electrical%20and%20electromechanical%20equipments.%0A*%C2%A0Information%20systems.%0A*%C2%A0Development%20of%20hardware%2C%0A*%C2%A0Design%20and%20construction%20of%20test%20benches%20and%20electronic%20cards.%0A%0A%23%20Process%20studies%0A%0A*%C2%A0Mechanical%20and%20electrical%0A*%C2%A0Handling.%0A*%C2%A0Automation%20and%20robotics.%0A*%C2%A0Tooling.%0A*%C2%A0Installation%20methods.%0A*%C2%A0Industrialisation%20studies.%0A*%C2%A0Electrical%20wiring%20methods.%0A).

**Comment by mt3o** [comment]
Thanks!
I hadn't spotted that hard space. Thanks, I'll be more careful about that.
Best regards!
