### ISSUE TITLE
RFC: Moving BacktickParser to a delimiter processor?

### ISSUE THREAD

**Issue by devnix** [thephpleague/commonmark#630]
**Description**
I'm implementing a Jira ticket format parser as an `InlineParserInterface`. I think I'm in the ballpark, but I've stumbled with this: I can't apply the transformation if the ticket name is between backticks, and I think the reason is that backticks are implemented as `InlineParserInterface` too.

If I'm understanding the docs, backticks would be ideally implemented as `DelimiterProcessorInterface`:
![image](https://user-images.githubusercontent.com/1777519/121378684-b3b66900-c943-11eb-9aa1-e155db9ba096.png)

- Do you think it would be reasonable to allow transformations to happen inside backticks?
- It would be a problem in terms of backwards compatibility?
- I think I could try to make a PR. I'm still not familiar with this package internals, so I would do my best.

**Example**
```markdown
test FOO-123 <!-- this will output 'test <a href="https://foo.atlassian.net/browse/FOO-123">FOO-123</a>' -->
```

```markdown
`test FOO-123` <!-- this will output '<pre>test FOO-123</pre>' -->
```

**Did this project help you today? Did it make you happy in any way?**

**Of course**. This is allowing me to do a cool view of our changelog for our non-programmer co-workers! I'm very thankful to have such control over the parsing, and I would love to contribute back if I can.

**Comment by colinodell** [comment]
Hey there!

> I can't apply the transformation if the ticket name is between backticks

This is intentional.  [According to the CommonMark specification](https://spec.commonmark.org/0.29/#example-340), "code span backticks have higher precedence than any other inline constructs except HTML tags and autolinks".  This ensures that you can place Markdown inside of inline code spans without it being interpreted as Markdown.

> Do you think it would be reasonable to allow transformations to happen inside backticks?

Unfortuantely that's not something we'll be able to directly support in the core of this library as it would violate the Markdown spec.

If you really want to add that functionality anyway, you do have a few options:

1. Register an event observer for the `DocumentPreParsedEvent` and do a simple find-and-replace
2. Register an event observer for the `DocumentParsedEvent`, look for any inline code elements, and perform the find-and-replace on them
3. Implement your own custom renderer for inline code elements that does the find-and-replace
4. Avoid using the included `BacktickParser` and create your own `DelimiterProcessorInterface` to handle backticks instead

I would recommend against option 4 unless you're okay with going against the CommonMark specification.  It would probably be fine for most users, but it could produce unusual, unexpected results in some cases.

I hope that helps!

> Of course. This is allowing me to do a cool view of our changelog for our non-programmer co-workers! I'm very thankful to have such control over the parsing, and I would love to contribute back if I can.

Thank you so much for sharing that! I always love hearing how other people are using this library.  That project sounds awesome!

**Comment by devnix** [comment]
>This is intentional. According to the CommonMark specification, "code span backticks have higher precedence than any other inline constructs except HTML tags and autolinks". This ensures that you can place Markdown inside of inline code spans without it being interpreted as Markdown.

Oh, understood! It makes a lot of sense. In the end, I guess that the feature I want is some kind of autolink if some text follows a specific format.

I'm not sure how to approach option 3, but I guess I'm checking out 1 and 2. Your feedback was very valuable for me!

Would you accept a PR for a Jira autolink extension?

**Comment by colinodell** [comment]
You know what... I think that `MentionExtension` will support what you're trying to do in the upcoming `2.0` release!  I think we changed it so that the `prefix` can be more than a single character:

```php
use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\Mention\MentionExtension;
use League\CommonMark\MarkdownConverter;

// Define your configuration
$config = [
    'mentions' => [
        // Jira issue mention configuration.
        // Sample Input:  `FOO-123`
        // Sample Output: `<a href="https://foo.atlassian.net/browse/FOO-123">FOO-123</a>`
        'jira_issue' => [
            'prefix'    => 'FOO-',
            'pattern'   => '\d+',
            'generator' => "https://foo.atlassian.net/browse/FOO-%d",
        ],
    ],
];

// Configure the Environment with all the CommonMark parsers/renderers
$environment = new Environment($config);
$environment->addExtension(new CommonMarkCoreExtension());

// Add the Mention extension.
$environment->addExtension(new MentionExtension());

// Instantiate the converter engine and start converting some Markdown!
$converter = new MarkdownConverter($environment);
echo $converter->convertToHtml('...');
```

I haven't tested this code but I _think_ it should work on the `2.0` branch if you'd like to give that a try :)  If for any reason it does not work, I would definitely be open to making any necessary changes.

> Would you accept a PR for a Jira autolink extension?

I'd prefer to keep any extensions as generic as possible, and I think the `MentionExtension` covers this case perfectly.  If not we can figure out a good solution :)

**Comment by devnix** [comment]
Oh well, I guess [`this`](example.com) is fine too, with reasonable limitations.

```markdown
Oh well, I guess [`this`](example.com) is fine too, with reasonable limitations.
```

```php
private function addLink(AbstractStringContainer $node, string $ticket): void
{
    $link = new Link($this->baseUrl.'/browse/'.$ticket);

    $nodeClass = get_class($node);
    $label = new $nodeClass($ticket);

    $link->appendChild($label);

    $node->insertBefore($link);
}
```

The `UrlAutolinkProcessor` has been a great resource!

**Comment by devnix** [comment]
Oh we just cross-posted! 😄 

I've tried a similar solution in 1.6 branch and it would just not work between backticks. I already have this working as an extension anyway, let me know if it can be valuable (it has the advantage of looking for every kind of tickets, not just ones starting with a determined string.

```php
$environment = Environment::createGFMEnvironment()
    ->addExtension(new JiraAutolinkExtension('https://foobar.atlassian.net'))
;

$converter = new MarkdownConverter($environment);
```

**Comment by markhalliwell** [comment]
Agreed, `MentionExtension` is probably the best solution for this as it was built exactly for these types of use cases. That being said, if you need it to render custom markup (i.e. code/pre inside the link, I'm guessing for visual differences), you may want to look at [Custom Callback-Based Parsers](https://commonmark.thephpleague.com/2.0/extensions/mentions/#custom-callback-based-parsers). The `generateMention(Mention $mention): ?AbstractInline` method allows you to return a custom `AbstractInline` object, which you can build yourself so that it can include other markup.

**Comment by devnix** [comment]
That's great, but the problem is that I don't have a constant prefix, so I have to check the whole document and find for patterns matching the regular expression 😃

**Comment by colinodell** [comment]
Gotcha, that makes sense.

Unfortunately, I do think that parsing Jira issues with arbitrary prefixes is not generic enough to bundle into this library, but if you do end up open-sourcing your extension we'd be happy to [feature it in our README](https://github.com/thephpleague/commonmark#community-extensions)! 🙂

**Comment by devnix** [comment]
Nice! Should I use the same namespace? For example: `League\CommonMark\Extension\JiraAutolink`

**Comment by colinodell** [comment]
No, you can use your own namespace and it should work fine.

**Comment by devnix** [comment]
I mean, would it be a good practice 😅

**Comment by colinodell** [comment]
Ah, yes it would :upside_down_face:
