### ISSUE TITLE
Indented HTML embedded in Markdown is treated as a code block

### ISSUE THREAD

**Issue by ramsey** [thephpleague/commonmark#708]
**Version(s) affected**: 2.0.2

**Description**  

When embedding HTML in Markdown, HTML that is indented appears to confuse the league/commonmark parser, which renders it as if it were a code block.

On babelmark, 18 of the parsers produce output similar to what I expect.

For the given Markdown:

```markdown
# Hello

This is a Markdown paragraph.

* List item 1
* List item 2

<div>
    <h2>HTML embedded in Markdown</h2>

    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <p>Aenean libero lectus, consectetur in sem in, dictum malesuada magna.</p>
    </div>
</div>
```

I expect something close to the following HTML produced:

```html
<h1>Hello</h1>
<p>This is a Markdown paragraph.</p>
<ul>
  <li>List item 1</li>
  <li>List item 2</li>
</ul>
<div>
  <h2>HTML embedded in Markdown</h2>
  <div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    <p>Aenean libero lectus, consectetur in sem in, dictum malesuada magna.</p>
  </div>
</div>
```

However, the following HTML is actually produced:

```html
<h1>Hello</h1>
<p>This is a Markdown paragraph.</p>
<ul>
<li>List item 1</li>
<li>List item 2</li>
</ul>
<div>
    <h2>HTML embedded in Markdown</h2>
<pre><code>&lt;div&gt;
    &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit.&lt;/p&gt;
    &lt;p&gt;Aenean libero lectus, consectetur in sem in, dictum malesuada magna.&lt;/p&gt;
&lt;/div&gt;
</code></pre>
</div>
```

**How to reproduce**  

Run `composer require league/commonmark` and then execute the following script:

```php
<?php

declare(strict_types=1);

use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\MarkdownConverter;

require_once 'vendor/autoload.php';

$environment = new Environment();
$environment->addExtension(new CommonMarkCoreExtension());

$converter = new MarkdownConverter($environment);

$content = <<<'MD'
# Hello

This is a Markdown paragraph.

* List item 1
* List item 2

<div>
    <h2>HTML embedded in Markdown</h2>

    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <p>Aenean libero lectus, consectetur in sem in, dictum malesuada magna.</p>
    </div>
</div>

MD;

echo $converter->convertToHtml($content);
```

**Comment by ramsey** [comment]
For what it's worth, GitHub Flavored Markdown appears to parse it the same way as league/commonmark: https://gist.github.com/ramsey/39c401384b8eff81426d9d99ad0d6333

As I [mentioned on Twitter](https://twitter.com/ramsey/status/1428718408653328394), the background here is that I'm migrating a blog from Kramdown to league/commonmark, so I'm finding these inconsistencies in the parsers. I'm fully aware that Kramdown is its own flavor of Markdown, though. If you choose not to incorporate some of its parsing idiosyncrasies into the league/commonmark core extension, then I might be convinced to see how much effort it would take to develop a Kramdown compatibility extension. 😉

**Comment by colinodell** [comment]
This is the expected behavior for all CommonMark-compliant parsers, as you can see from [the Babelmark output](https://babelmark.github.io/?text=%23+Hello%0A%0AThis+is+a+Markdown+paragraph.%0A%0A*+List+item+1%0A*+List+item+2%0A%0A%3Cdiv%3E%0A++++%3Ch2%3EHTML+embedded+in+Markdown%3C%2Fh2%3E%0A%0A++++%3Cdiv%3E%0A++++++++%3Cp%3ELorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit.%3C%2Fp%3E%0A++++++++%3Cp%3EAenean+libero+lectus%2C+consectetur+in+sem+in%2C+dictum+malesuada+magna.%3C%2Fp%3E%0A++++%3C%2Fdiv%3E%0A%3C%2Fdiv%3E) (everything with the MD logo is CommonMark-compliant).

According to the spec, the blank line immediately following the `<h2>` signals the end of that [type 6 HTML block](https://spec.commonmark.org/0.30/#html-block).  The line after that is indented with 4 spaces, so it fails to meet the "(after up to three optional spaces of indentation)" start condition and is instead parsed as indented code.

[Examples 190 and 191](https://spec.commonmark.org/0.30/#example-190) confirm this behavior and demonstrate that ideally the HTML would not be indented or not contain empty lines in the middle.

If you did want to continue using this library, my recommendation would be to de-indent any lines starting with HTML tags.  One possibility would be [registering a custom event listener](https://commonmark.thephpleague.com/2.0/customization/event-dispatcher/#registering-listeners) for the `DocumentPreParsedEvent` which does a simple regex find-and-replace for that indentation:

```php
final class StripIndentationFromLikelyHtmlBlocksListener
{
    public function __invoke(DocumentPreParsedEvent $event): void
    {
        $content = $event->getMarkdown()->getContent();
        $content = \preg_replace('/^ +</', '<', $content);
        $event->replaceMarkdown($content);
    }
}
```

It's not the most accurate approach as the regex here is very naive, but it is the easiest to implement and requires no changes to or overriding of the core library.

Alternatively, you could decorate the `HtmlBlockStartParser` so that it doesn't know whether the line is indented:

```php
final class HtmlBlockStartRegardlessOfIndentationParser implements BlockStartParserInterface
{
    private HtmlBlockStartParser $inner;

    public function __construct(HtmlBlockStartParser $inner)
    {
        $this->inner = $inner;
    }

    public function tryStart(Cursor $cursor, MarkdownParserStateInterface $parserState): ?BlockStart
    {
        // Always consume any amount of leading indentation so the main parser doesn't know it's indented
        $cursor->advanceToNextNonSpaceOrTab();

        return $this->innert->tryStart($cursor, $parserState);
    }
}
````

This would be a more accurate approach.  I _think_ you'd then register that parser with a priority of 1 higher than the default one (40 + 1 = 41) which should cause it to run first and give you the behavior you're looking for.

**Comment by ramsey** [comment]
Would there be a way to detect the start and end of HTML tags and treat everything within them as raw HTML, so that it doesn't attempt to parse the HTML as Markdown?

**Comment by colinodell** [comment]
No, unfortunately not.  This is because we parse the Markdown one line at a time.  When it reaches that blank line, `HtmlBlockParser::tryContinue()` is called to determine if the block should continue onto that line.  This is the only opportunity we have to decide if we should keep parsing as HTML or let the other block parser take a stab at it.  Based on the spec, we decide the block has ended if the line is blank.  You could certainly override that decision, but then you wouldn't have a way to see if the line after _that_ is also HTML, so you'll end up mis-parsing subsequent lines as HTML regardless of whether they truly do contain HTML.

I think a de-indenting approach is probably your best bet here.

**Comment by ramsey** [comment]
It looks like I don't have to de-indent. I can get rid of the empty lines, and this also solves the problem.

**Comment by colinodell** [comment]
That works too :)
