### ISSUE TITLE
PHPUnit fails to mark some ending curly braces as being covered code

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#75]
[For example](https://scrutinizer-ci.com/g/thephpleague/commonmark/code-structure/master/class/League%5CCommonMark%5CBlock%5CParser%5CAbstractBlockParser):

![2015-02-24_14-01-52](https://cloud.githubusercontent.com/assets/202034/6356771/b7958cc4-bc2d-11e4-9308-a17e2ee8106d.png)

This is causing our code coverage to be a bit lower than it really is.

Maybe we've got a bad configuration in phpunit.xml or something?  I'm not really sure.

**Comment by ptlis** [comment]
I've encountered similar issues in the past - but never in such a simple case. 

As I understand it's due to limitations in how xdebug marks potentially executable lines & tracks lines that have been executed.

One possible (but ugly) work-around is to use the @codeCoverageIgnoreEnd annotation as described in [PHPUnit's documentation](https://phpunit.de/manual/current/en/code-coverage-analysis.html).

**Comment by krues8dr** [comment]
What version of XDebug are you running?  I remember [an old version had this problem](http://bugs.xdebug.org/view.php?id=766).

**Comment by colinodell** [comment]
Looks like it's version 2.2.7: https://travis-ci.org/thephpleague/commonmark/jobs/58317953#L92 (line 92)

**Comment by krues8dr** [comment]
I just ran it through Xdebug v2.3.2 and [got 100% on that file](https://gist.github.com/krues8dr/c11679a36e40f632f18b), correctly reporting the end lines as dead code.     So I'm guessing this is an out-of-date Xdebug issue.

**Comment by colinodell** [comment]
Because it looks like this is an xdebug issue (possibly an out-of-date one), there's really nothing we can do here, so I'm going to close this issue.  Thanks to everyone for looking into this!
