### ISSUE TITLE
HTML elements within <pre> tags

### ISSUE THREAD

**Issue by ohreally** [thephpleague/commonmark#753]
### Description

Both the `<pre>` and `<code>` HTML tags allow for embedded HTML (_phrasing content_). Markdown parsers tend to unconditionally replace all angle brackets with their HTML entities within `<pre>` and/or `<code>` tags, invalidating all embedded HTML.

However, I would really like to be able to use emphasis (bold, italic, etc.) in the code examples I publish.

It would be cool if I could configure which tags to allow in code blocks. I wouldn't mind having to use HTML, if it is complicated or undesirable to allow Markdown. Nor would I mind having only a subset of the tags that are allowed by the HTML spec (e.g. `<a>`, `<em>`, `<mark>`, `<small>`, `<strong>`, `<sub>`, `<sup>` and `<u>`).

To be clear: while current behaviour is not in line with the HTML spec, it is in line with the official Markdown documentation.

Some related links that may save you some time:

`<pre>`, `<code>` and _phrasing content_ specs at [whatwg.org](https://html.spec.whatwg.org/multipage/):
- [The `pre` element](https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element)
- [The `code` element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element)
- [Phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content)

`<pre>`, `<code>` and _phrasing content_ specs at [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML):
- [The Preformatted Text element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre)
- [The Inline Code element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code)
- [Phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content)

Related Markdown documentation:
- [Code Blocks](https://daringfireball.net/projects/markdown/syntax#precode)

Thanks for considering!

Rob

### Example

A tiny example, taken from my blog.<br>
I'm showing how to use the machine architecture to select the correct directory (for kernel configuration).

What I would like to do is this:

```
# uname -m
**amd64**

# cd /usr/src/sys/**amd64**/conf
```

(Triple backticks not shown.)

This would then render **amd64** in bold (without the asterisks, of course), making it clear for the user what to verify/use.

### Did this project help you today? Did it make you happy in any way?

CommonMark is helping me to finally switch from WordPress to a homegrown solution. I just started a week ago, and I'm still learning, but so far I like it. A lot. :)

**Comment by colinodell** [comment]
Thanks for the detailed suggestion!

As you noted, this does contradict the CommonMark spec which says that "the content of a code fence is treated as literal text, not parsed as inlines".  I generally try to avoid going against the spec unless:

1. The functionality would be opt-in to ensure users get vanilla CommonMark behavior by default
2. The requested functionality is useful to a broad audience
3. The impact of that new functionality on the rest of the core library is minimal

In this case, I'm not sure that bullet point 3 can be accomplished because of how the `FencedCode` and `IndentedCode` classes and their parsers/renderers currently work: they're built on the assumption that there's never any Markdown inside of them needing to be parsed.  There are two ways you could work around this:

1. Create specialized code block node types, then replace `FencedCodeParser`, FencedCodeStartParser`, `IndentedCodeParser`, and `IndentedCodeStartParser` with custom versions that allow inlines to be added; or,
2. Create specialized code block node types, create an event listener to manually adjust the AST, and have that convert the block types and perform additional inline parsing yourself outside of the main parsing.

Because both approaches deviate a bit heavily from how the library works today, I unfortunately wouldn't want to include that functionality in the core library.  It's certainly doable to implement in a custom extension, but it's just not a great fit for the goals of this library right now.

> CommonMark is helping me to finally switch from WordPress to a homegrown solution. I just started a week ago, and I'm still learning, but so far I like it. A lot. :)

Thank you, I really appreciate those kind words, and I'm very sorry we can't implement this directly within the main library.

**Comment by ohreally** [comment]
Then I guess the easier solution would be to use HTML for the entire block. It's ugly, but at least it works.

Thanks anyway.
