### ISSUE TITLE
Improper parsing of lists in Markdown if they don't start with 1.

### ISSUE THREAD

**Issue by Danon** [thephpleague/commonmark#832]
### Version(s) affected

2.2

### Description

Proper prasing of lists happen only if the list starts with `1.`. If lists starts with other number, the parsing isn't correct.

### How to reproduce

This markdown
```md
One:
1. One
2. One 

Two
3. Two
5. Two
```

by Markdown and CommonMark should result in something in shape of
```html
<p>One</p>
<ol>
 <li>One</li>
 <li>One</li>
</ol>
<p>Two</p>
<ol>
 <li>Two</li>
 <li>Two</li>
</ol>
```

But it doesn't. If you change `3.` and `4.` to `1.` and `2.` then it is properly parsed (the numbered lines are parsed as parapgraph, not a list). In my opinion, it should be properly parsed for `3.` and `4.` as well.
If you add an empty line between `Two` and `3. Two` then again, it's properly parsed. But it should also be properly parsed in the absence of the blank line.

**Comment by colinodell** [comment]
Hi @Danon,

Thanks for the detailed submission!  The behavior you're experiencing is required by [the CommonMark specification](https://spec.commonmark.org/0.30/#list-items) that ([we (and many other parsers) follow](https://babelmark.github.io/?text=One%3A%0A1.+One%0A2.+One+%0A%0ATwo%0A3.+Two%0A5.+Two):

![image](https://user-images.githubusercontent.com/202034/157986592-080aa6a7-2452-4417-a1c9-6fccc06dcec2.png)

[This requirement was originally added to the spec](https://github.com/commonmark/commonmark-spec/commit/0ff8022808be1aca10088eff529d00727b3e1ad6) in their [0.26 release](https://github.com/commonmark/commonmark-spec/releases/tag/0.26) which we're required to follow in order to be fully compliant:

> Ordered list markers that interrupt a paragraph must start with 1.

The rationale is that it's common to have paragraphs that span multiple lines like this:

```md
This is one paragraph
spread across two lines.
```

Or even:

```md
In the TV show "Lost", certain numbers showed
up repeatedly - they were 4, 8, 15, 16, 23 and
42. Fans call these "The Numbers".
```

The line starting with `42.` could be perceived as a list item, but its far more likely the author was simply continuing a paragraph.

I believe the spec maintainers decided to make an exception to this rule if, and only if, the next line starts with `1.`.  I'd guess that's because of all the possible numbers that could appear in a sentence, if you see `1.` then it's _probably_ a list; otherwise, we assume it's a paragraph continuation.

In order to break the paragraph continuation in your sample input you'll want to add a blank line after `Two`:

```md
One:
1. One
2. One 

Two

3. Two
5. Two
```

Hope that helps!

**Comment by Danon** [comment]
Thanks @colinodell you're awesome.
