### ISSUE TITLE
BlockQuote is not rendering correct in GithubFlavoredMarkdownExtension

### ISSUE THREAD

**Issue by basteyy** [thephpleague/commonmark#965]
### Version(s) affected

2.3.9

### Description

Input:
```
The text

> Blockquote Line 1
> Blockquote Line 2

The other Text
```

Expected output (the result on github.com)
```
<p>The text</p>
<blockquote>
<p>Blockquote Line 1<br>
Blockquote Line 2</p>
</blockquote>
<p>The other Text</p>
```

Current Output:
```
<p>The text</p>
<blockquote>
<p>Blockquote Line 1
Blockquote Line 2</p>
</blockquote>
<p>The other Text</p>
```

Alternative output could be:
```
<p>The text</p>
<blockquote>
<p>Blockquote Line 1</p>
<p>Blockquote Line 2</p>
</blockquote>
<p>The other Text</p>
```

### How to reproduce

```php
$environment = new Environment();
$environment->addExtension(new CommonMarkCoreExtension());
$environment->addExtension(new GithubFlavoredMarkdownExtension());
$converter = new MarkdownConverter($environment);
echo $converter->convert('The text

> Blockquote Line 1
> Blockquote Line 2

The other Text');
```

**Comment by colinodell** [comment]
[The CommonMark spec](https://spec.commonmark.org/0.30/#example-243) says that the blockquote should be rendered as a single paragraph with a [soft break](https://spec.commonmark.org/0.30/#soft-line-breaks) separating the two lines. If we run your Markdown through [our `XmlRenderer`](https://commonmark.thephpleague.com/2.3/xml/) instead we see that it indeed separates the two lines with a soft break:

```
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://commonmark.org/xml/1.0">
    <paragraph>
        <text>The text</text>
    </paragraph>
    <block_quote>
        <paragraph>
            <text>Blockquote Line 1</text>
            <softbreak />
            <text>Blockquote Line 2</text>
        </paragraph>
    </block_quote>
    <paragraph>
        <text>The other Text</text>
    </paragraph>
</document>
```

Which matches [how the JS reference parser handles this](https://spec.commonmark.org/dingus/?text=The%20text%0A%0A%3E%20Blockquote%20Line%201%0A%3E%20Blockquote%20Line%202%0A%0AThe%20other%20Text) (see the AST tab).  Indeed, [all CommonMark-compliant parsers seem to handle this case the same way](https://babelmark.github.io/?text=The+text%0A%0A%3E+Blockquote+Line+1%0A%3E+Blockquote+Line+2%0A%0AThe+other+Text).

My best guess is that GitHub.com might have their GFM parser to render those soft breaks as hard breaks (`<br>`) instead of `\n`.  If you'd like that same behavior, you can set the `renderer` &raquo; `soft_break` [configuration option](https://commonmark.thephpleague.com/2.3/configuration/) accordingly:

```php
$environment = new Environment([
    'renderer' => [
        'soft_break' => '<br>',
    ],
]);
$environment->addExtension(new CommonMarkCoreExtension());
$environment->addExtension(new GithubFlavoredMarkdownExtension());
$converter = new MarkdownConverter($environment);
echo $converter->convert('The text

> Blockquote Line 1
> Blockquote Line 2

The other Text');
```

Give that a try and let me know if that helps!

**Comment by basteyy** [comment]
> Give that a try and let me know if that helps!

Yes, that helps with my issue. Thanks for the explaining as well. 

> My best guess is that GitHub.com might have their GFM parser to render those soft breaks as hard breaks (`<br>`) instead of `\n`. If you'd like that same behavior, you can set the `renderer` » `soft_break` [configuration option](https://commonmark.thephpleague.com/2.3/configuration/) accordingly:

Perhaps the GFM should be used hard breaks by default? Or perhaps I'm the only one who was/is confused about the difference. 

Anyway, thanks a lot :-)

**Comment by colinodell** [comment]
> Yes, that helps with my issue. Thanks for the explaining as well.

Great! I'm glad I could help :)

> Perhaps the GFM should be used hard breaks by default? Or perhaps I'm the only one who was/is confused about the difference.

:thinking: I'm inclined to keep the current behavior as-is, primarily because it matches the out-of-box behavior of their parser (even if they might configure it differently when using it on their site).  But if anyone else stumbles upon this issue in the future and makes a strong case in favor of this idea, I will certainly consider it.
