### ISSUE TITLE
Weird glitch with Footnote Extension

### ISSUE THREAD

**Issue by thrhgh** [thephpleague/commonmark#977]
### Version(s) affected

2.4

### Description

Hi. I am using Commonmark 2.4 and I have this weird issue after upgrading from 1.6:

The following is rendered correctly:

```
Some example text[^1].

[^1]: [Referene to a paper.](https://doi.org/10.1016/S1474-4422(06)70497-5)

```

and the following is rendered incorrectly without converting the footnotes:

```
Some example text[^1].

**Referenzen**
[^1]: [Referene to a paper.](https://doi.org/10.1016/S1474-4422(06)70497-5)
```

### How to reproduce

Some example text[^1].

**Referenzen**
[^1]: [Referene to a paper.](https://doi.org/10.1016/S1474-4422(06)70497-5)

**Comment by colinodell** [comment]
Babelmark3 confirms that we handle this differently than GitHub's GFM implementation:

![image](https://github.com/thephpleague/commonmark/assets/202034/cf5c0944-91f6-423b-8654-25f831f8b767)

Unfortunately the GFM spec doesn't anything about footnote functionality, so we'll need to decide whether/how to follow their implementation anyway, assuming it follows the other principles of the spec.  More research is needed here.

**Comment by colinodell** [comment]
After further investigation, it seems this library is working as expected. [According to our spec](https://github.com/thephpleague/commonmark/blob/795851fa43b6981f7e751ae714788078075b2bbb/tests/functional/Extension/Footnote/spec.txt#L167-L171):

> Footnotes should be separated from other blocks with blank lines

We do this because the syntax for footnotes is virtually identical to [link reference definitions](https://github.github.com/gfm/#link-reference-definition) which [cannot interrupt a paragraph](https://github.github.com/gfm/#example-182).  In other words, if it cannot be parsed as a valid link reference then it cannot be a footnote.

I also tested your input against [`cmark-gfm` - the "official" implementation of GFM](https://github.com/github/cmark-gfm) - which gave the same results as this library.

**Comment by colinodell** [comment]
Note that GitHub.com does do some additional pre- and post-processing outside of `cmark-gfm` to support certain features on their site.  This special processing is not documented in the official GFM specification.  That's why we have our own spec for footnotes which tries to stay close to GitHub.com's behavior without violating the actual, official specifications.
